### ISSUE TITLE
ACT Oracle export fails

### ISSUE THREAD

**Issue by dvdrndlph** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#130]
Phenotype version not set correctly in latest release. I see this error output :

```
-----------------------------------------
Exporting data
processing output file: MANIFEST.csv

Execute SQL -----------------------------



--OUTPUT_FILE: MANIFEST.csv
SELECT distinct 'UIC' as SITE_ABBREV,
   'University of Illinois at Chicago'    AS SITE_NAME,
   'David Randolph' as CONTACT_NAME,
   'drando2@uic.edu' as CONTACT_EMAIL,
   'ACT' as CDM_NAME, ---- hardwired null for ACT
   '1.7.12a' as CDM_VERSION,
   null AS VOCABULARY_VERSION, -- hardwired null for ACT
   'Y' as N3C_PHENOTYPE_YN,
   phenotype_version  as N3C_PHENOTYPE_VERSION,
   CAST(SYSDATE as date) as RUN_DATE,
   CAST( (SYSDATE + NUMTODSINTERVAL(-1, 'day')) as date) as UPDATE_DATE,	--change integer based on your site's data latency
   CAST( (SYSDATE + NUMTODSINTERVAL(7, 'day')) as date) as NEXT_SUBMISSION_DATE FROM DUAL
-----------------------------------------
Traceback (most recent call last):
  File "./db_exp.py", line 288, in <module>
    db_export(db_conn, exp['sql'], csvwriter, arraysize, debug)
  File "./db_exp.py", line 119, in db_export
    cursor.execute(sql);
cx_Oracle.DatabaseError: ORA-00904: "PHENOTYPE_VERSION": invalid identifier
```

Nothing in N3C_extract_act_oracle.sql is pulling the PHENOTYPE_VERSION.

**Comment by empfff** [comment]
fixed, thanks for the catch!
